// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SongAIContext {
    "file_name"?: string;
    "source_ref"?: string;
    "source_url"?: string;
    "source_kind"?: string;
    "source_title"?: string;
    "source_uploader"?: string;
    "source_channel"?: string;
    "library_root"?: string;
    "source_description_hint"?: string;
    "duration_seconds"?: number | null;
    "duration_hint"?: string;
    "has_transcript"?: boolean;
    "has_timestamped_transcript"?: boolean;
    "input_text"?: string;
    "user_context"?: string;
    "artist_hint"?: string;
    "album_hint"?: string;
    "title_hint"?: string;
    "year_hint"?: number | null;
    "genre_hint"?: string;
    "track_number_hint"?: number | null;
    "notes"?: string;
    "resolved_title"?: string;
    "resolved_artist"?: string;
    "resolved_album"?: string;
    "resolved_track_number"?: string;
    "resolved_year"?: string;
    "resolved_genre"?: string;
    "resolved_confidence"?: string;
    "resolved_notes"?: string;
    "target_artist_dir"?: string;
    "target_album_dir"?: string;
    "target_base_name"?: string;
    "target_audio_path"?: string;
    "target_lyrics_path"?: string;
    "target_timed_lyrics_path"?: string;
    "target_metadata_path"?: string;

    /** Creates a new SongAIContext instance. */
    constructor($$source: Partial<SongAIContext> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SongAIContext instance from a string or object.
     */
    static createFrom($$source: any = {}): SongAIContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SongAIContext($$parsedSource as Partial<SongAIContext>);
    }
}
