// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../melodex/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "melodex:job-progress": main$0.JobProgressEvent;
            "melodex:playback": main$0.PlaybackState;
            "melodex:state": main$0.AppState;
        }
    }
}
