//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../melodex/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "melodex:job-progress": $$createType0,
        "melodex:playback": $$createType1,
        "melodex:state": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = main$0.JobProgressEvent.createFrom;
const $$createType1 = main$0.PlaybackState.createFrom;
const $$createType2 = main$0.AppState.createFrom;

configure();
