// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTrackToPlaybackQueue(trackID: string): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(327180266, trackID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddTrackToPlaylist(playlistID: string, trackID: string): $CancellablePromise<$models.Playlist> {
    return $Call.ByID(1914060488, playlistID, trackID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ApplyArtworkFromFile(trackID: string, sourcePath: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(831302307, trackID, sourcePath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BuildLibraryManifest previews the metadata-only backup payload for the
 * current local catalog. It does not write or upload anything; file export and
 * remote sync can build on this contract after their confirmation/security
 * flows are selected.
 */
export function BuildLibraryManifest(): $CancellablePromise<$models.LibraryManifest> {
    return $Call.ByID(385956135).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CheckForUpdates(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2675659504).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ClearAPIKey(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(581403093).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ClearImportHistory(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2359515561).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ClearPlaybackQueue(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(4007611798).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreatePlaylist(name: string, description: string): $CancellablePromise<$models.Playlist> {
    return $Call.ByID(3989260235, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteAllJobs(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2262497241).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteDoneJobs(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2100458170).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteJob(jobID: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(4227809653, jobID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeletePlaylist(playlistID: string): $CancellablePromise<void> {
    return $Call.ByID(239328020, playlistID);
}

export function DeleteQueuedJobs(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1076743371).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DownloadTrackVideo(trackID: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(3148156267, trackID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * EvaluateSmartPlaylist previews a local smart-playlist definition against a
 * catalog snapshot. Listening context is currently empty because persisted
 * listening statistics are not yet part of the product schema; callers can
 * still use all metadata and file-health predicates offline.
 */
export function EvaluateSmartPlaylist(definition: $models.SmartPlaylistDefinition): $CancellablePromise<$models.SmartPlaylistEvaluation> {
    return $Call.ByID(134630049, definition).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ExportDiagnostics(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(4266831633).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * FindDuplicateCandidates returns explainable, non-destructive suggestions for
 * one catalog track. The caller must still ask the user whether to keep,
 * reprocess, or import anything; this method never mutates the catalog.
 */
export function FindDuplicateCandidates(trackID: string, threshold: number): $CancellablePromise<$models.DuplicateMatch[]> {
    return $Call.ByID(3273166213, trackID, threshold).then(($result: any) => {
        return $$createType6($result);
    });
}

export function FindURLImportDuplicate(url: string): $CancellablePromise<$models.URLImportDuplicateInfo> {
    return $Call.ByID(1130563811, url).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetPlaylists(): $CancellablePromise<$models.Playlist[]> {
    return $Call.ByID(843334910).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetState(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2490316256).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InspectBundle(path: string): $CancellablePromise<$models.TrackRecord> {
    return $Call.ByID(2083242935, path).then(($result: any) => {
        return $$createType9($result);
    });
}

export function InspectTrack(metadataPath: string): $CancellablePromise<$models.TrackPreview> {
    return $Call.ByID(3015039486, metadataPath).then(($result: any) => {
        return $$createType10($result);
    });
}

export function LogUIEvent(event: string, name: string, $from: string): $CancellablePromise<void> {
    return $Call.ByID(3235220805, event, name, $from);
}

export function LogVideoEvent(event: string, source: string, detail: string): $CancellablePromise<void> {
    return $Call.ByID(2149041088, event, source, detail);
}

export function MediaInfo(path: string): $CancellablePromise<$models.MediaFileInfo> {
    return $Call.ByID(4007559423, path).then(($result: any) => {
        return $$createType11($result);
    });
}

export function MediaURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(1112958668, path);
}

/**
 * MediaURLInfo is the typed URL-creation contract. MediaURL is retained as a
 * compatibility method for older clients, but all new callers can receive
 * the URL, backend MIME type, file size, and token expiry together.
 */
export function MediaURLInfo(path: string): $CancellablePromise<$models.MediaFileInfo> {
    return $Call.ByID(3920892880, path).then(($result: any) => {
        return $$createType11($result);
    });
}

export function MovePlaylistTrack(playlistID: string, trackID: string, delta: number): $CancellablePromise<$models.Playlist> {
    return $Call.ByID(3710755937, playlistID, trackID, delta).then(($result: any) => {
        return $$createType1($result);
    });
}

export function MoveTrackInPlaybackQueue(trackID: string, delta: number): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(2402112236, trackID, delta).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3584934946, url);
}

export function PauseAllJobs(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1499510268).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PausePlayback(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(2048075820).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PickArtworkFile(): $CancellablePromise<string> {
    return $Call.ByID(2856068662);
}

export function PickCookiesFile(): $CancellablePromise<string> {
    return $Call.ByID(130405697);
}

export function PickLibraryRoot(): $CancellablePromise<string> {
    return $Call.ByID(2984071479);
}

export function PickLocalFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(2543529458).then(($result: any) => {
        return $$createType12($result);
    });
}

export function PickLocalFolder(): $CancellablePromise<string> {
    return $Call.ByID(2236559743);
}

export function PlayNext(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1329581570).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayPrevious(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(2794268494).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayTrack(trackID: string, queueTrackIDs: string[], queueSource: string): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(595420586, trackID, queueTrackIDs, queueSource).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QueueLocalFiles(paths: string[]): $CancellablePromise<$models.Job[]> {
    return $Call.ByID(2921415522, paths).then(($result: any) => {
        return $$createType14($result);
    });
}

export function QueueURLImport(url: string): $CancellablePromise<$models.Job> {
    return $Call.ByID(1659137272, url).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ReadFileDataURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(3641447236, path);
}

export function RemoveTrackFromPlaybackQueue(trackID: string): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1575307248, trackID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveTrackFromPlaylist(playlistID: string, trackID: string): $CancellablePromise<$models.Playlist> {
    return $Call.ByID(3077703482, playlistID, trackID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RenamePlaylist(playlistID: string, name: string, description: string): $CancellablePromise<$models.Playlist> {
    return $Call.ByID(4227227869, playlistID, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RepairLibraryFiles(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(3118196622).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReprocessTrackWithContext(trackID: string, userContext: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1045238311, trackID, userContext).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReprocessUnprocessedTracks(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(3772089250).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RescanLibrary(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(885484524).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ResetSettings(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(3018254949).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RetryFailedPlaylistItems(rootID: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2928844458, rootID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(77851903, path);
}

export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1949631069, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ScanLibraryHealth returns a deterministic read-only report over the current
 * catalog. It deliberately does not apply any proposed fix or rewrite files.
 */
export function ScanLibraryHealth(): $CancellablePromise<$models.LibraryHealthReport> {
    return $Call.ByID(3755752605).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SeekPlayback(ratio: number): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1362807640, ratio).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetPlaybackVolume(value: number): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1158710528, value).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetShuffleEnabled(enabled: boolean): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(2925054125, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ShufflePlaybackQueue(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(361662082).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartJob(jobID: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2066873134, jobID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StopJob(jobID: string): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1508425892, jobID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function TestAI(): $CancellablePromise<string> {
    return $Call.ByID(2104518583);
}

export function TestFFmpeg(): $CancellablePromise<string> {
    return $Call.ByID(222458128);
}

export function TestYTDLP(): $CancellablePromise<string> {
    return $Call.ByID(2745920776);
}

export function ToggleMute(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(232514796).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TogglePlayback(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(3649584132).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ToggleRepeatMode(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(2179605337).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ToggleShuffle(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1977499334).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ToggleWindowMaximise(): $CancellablePromise<void> {
    return $Call.ByID(3967369578);
}

// Private type creation functions
const $$createType0 = $models.PlaybackState.createFrom;
const $$createType1 = $models.Playlist.createFrom;
const $$createType2 = $models.AppState.createFrom;
const $$createType3 = $models.LibraryManifest.createFrom;
const $$createType4 = $models.SmartPlaylistEvaluation.createFrom;
const $$createType5 = $models.DuplicateMatch.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.URLImportDuplicateInfo.createFrom;
const $$createType8 = $Create.Array($$createType1);
const $$createType9 = $models.TrackRecord.createFrom;
const $$createType10 = $models.TrackPreview.createFrom;
const $$createType11 = $models.MediaFileInfo.createFrom;
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $models.Job.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.LibraryHealthReport.createFrom;
