// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as songstore$0 from "./internal/songstore/models.js";

export class AppState {
    "settings": PublicSettings;
    "stats": LibraryStats;
    "health": LibraryHealth;
    "workers": WorkerStats;
    "genreBuckets": FacetBucket[];
    "yearBuckets": FacetBucket[];
    "buildInfo": BuildInfo;
    "updateInfo": UpdateInfo;
    "diagnostics": DiagnosticsInfo;
    "aiStatus": string;
    "jobs": Job[];
    "importHistory": ImportHistoryEntry[];
    "libraryTracks": TrackRecord[];
    "recentTracks": TrackRecord[];
    "playlists": Playlist[];
    "playback": PlaybackState;
    "promptFiles": PromptInfo[];
    "toolStatus": ToolStatus;
    "toolReadiness": { [_ in string]?: ToolReadiness };
    "rootInfo": RootInfo;
    "windowFullscreen": boolean;

    /** Creates a new AppState instance. */
    constructor($$source: Partial<AppState> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = (new PublicSettings());
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new LibraryStats());
        }
        if (!("health" in $$source)) {
            this["health"] = (new LibraryHealth());
        }
        if (!("workers" in $$source)) {
            this["workers"] = (new WorkerStats());
        }
        if (!("genreBuckets" in $$source)) {
            this["genreBuckets"] = [];
        }
        if (!("yearBuckets" in $$source)) {
            this["yearBuckets"] = [];
        }
        if (!("buildInfo" in $$source)) {
            this["buildInfo"] = (new BuildInfo());
        }
        if (!("updateInfo" in $$source)) {
            this["updateInfo"] = (new UpdateInfo());
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = (new DiagnosticsInfo());
        }
        if (!("aiStatus" in $$source)) {
            this["aiStatus"] = "";
        }
        if (!("jobs" in $$source)) {
            this["jobs"] = [];
        }
        if (!("importHistory" in $$source)) {
            this["importHistory"] = [];
        }
        if (!("libraryTracks" in $$source)) {
            this["libraryTracks"] = [];
        }
        if (!("recentTracks" in $$source)) {
            this["recentTracks"] = [];
        }
        if (!("playlists" in $$source)) {
            this["playlists"] = [];
        }
        if (!("playback" in $$source)) {
            this["playback"] = (new PlaybackState());
        }
        if (!("promptFiles" in $$source)) {
            this["promptFiles"] = [];
        }
        if (!("toolStatus" in $$source)) {
            this["toolStatus"] = (new ToolStatus());
        }
        if (!("toolReadiness" in $$source)) {
            this["toolReadiness"] = {};
        }
        if (!("rootInfo" in $$source)) {
            this["rootInfo"] = (new RootInfo());
        }
        if (!("windowFullscreen" in $$source)) {
            this["windowFullscreen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     */
    static createFrom($$source: any = {}): AppState {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType12;
        const $$createField12_0 = $$createType14;
        const $$createField13_0 = $$createType14;
        const $$createField14_0 = $$createType16;
        const $$createField15_0 = $$createType17;
        const $$createField16_0 = $$createType19;
        const $$createField17_0 = $$createType20;
        const $$createField18_0 = $$createType22;
        const $$createField19_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField1_0($$parsedSource["stats"]);
        }
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField2_0($$parsedSource["health"]);
        }
        if ("workers" in $$parsedSource) {
            $$parsedSource["workers"] = $$createField3_0($$parsedSource["workers"]);
        }
        if ("genreBuckets" in $$parsedSource) {
            $$parsedSource["genreBuckets"] = $$createField4_0($$parsedSource["genreBuckets"]);
        }
        if ("yearBuckets" in $$parsedSource) {
            $$parsedSource["yearBuckets"] = $$createField5_0($$parsedSource["yearBuckets"]);
        }
        if ("buildInfo" in $$parsedSource) {
            $$parsedSource["buildInfo"] = $$createField6_0($$parsedSource["buildInfo"]);
        }
        if ("updateInfo" in $$parsedSource) {
            $$parsedSource["updateInfo"] = $$createField7_0($$parsedSource["updateInfo"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField8_0($$parsedSource["diagnostics"]);
        }
        if ("jobs" in $$parsedSource) {
            $$parsedSource["jobs"] = $$createField10_0($$parsedSource["jobs"]);
        }
        if ("importHistory" in $$parsedSource) {
            $$parsedSource["importHistory"] = $$createField11_0($$parsedSource["importHistory"]);
        }
        if ("libraryTracks" in $$parsedSource) {
            $$parsedSource["libraryTracks"] = $$createField12_0($$parsedSource["libraryTracks"]);
        }
        if ("recentTracks" in $$parsedSource) {
            $$parsedSource["recentTracks"] = $$createField13_0($$parsedSource["recentTracks"]);
        }
        if ("playlists" in $$parsedSource) {
            $$parsedSource["playlists"] = $$createField14_0($$parsedSource["playlists"]);
        }
        if ("playback" in $$parsedSource) {
            $$parsedSource["playback"] = $$createField15_0($$parsedSource["playback"]);
        }
        if ("promptFiles" in $$parsedSource) {
            $$parsedSource["promptFiles"] = $$createField16_0($$parsedSource["promptFiles"]);
        }
        if ("toolStatus" in $$parsedSource) {
            $$parsedSource["toolStatus"] = $$createField17_0($$parsedSource["toolStatus"]);
        }
        if ("toolReadiness" in $$parsedSource) {
            $$parsedSource["toolReadiness"] = $$createField18_0($$parsedSource["toolReadiness"]);
        }
        if ("rootInfo" in $$parsedSource) {
            $$parsedSource["rootInfo"] = $$createField19_0($$parsedSource["rootInfo"]);
        }
        return new AppState($$parsedSource as Partial<AppState>);
    }
}

export class BuildInfo {
    "appVersion": string;
    "buildNumber": string;
    "gitCommit": string;
    "buildTime": string;
    "releaseChannel": string;
    "goVersion": string;
    "settingsSchemaVersion": number;
    "catalogSchemaVersion": number;
    "libraryCacheSchemaVersion": number;
    "playlistSchemaVersion": number;
    "importHistorySchemaVersion": number;
    "trackMetadataSchemaVersion": number;

    /** Creates a new BuildInfo instance. */
    constructor($$source: Partial<BuildInfo> = {}) {
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("buildNumber" in $$source)) {
            this["buildNumber"] = "";
        }
        if (!("gitCommit" in $$source)) {
            this["gitCommit"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }
        if (!("releaseChannel" in $$source)) {
            this["releaseChannel"] = "";
        }
        if (!("goVersion" in $$source)) {
            this["goVersion"] = "";
        }
        if (!("settingsSchemaVersion" in $$source)) {
            this["settingsSchemaVersion"] = 0;
        }
        if (!("catalogSchemaVersion" in $$source)) {
            this["catalogSchemaVersion"] = 0;
        }
        if (!("libraryCacheSchemaVersion" in $$source)) {
            this["libraryCacheSchemaVersion"] = 0;
        }
        if (!("playlistSchemaVersion" in $$source)) {
            this["playlistSchemaVersion"] = 0;
        }
        if (!("importHistorySchemaVersion" in $$source)) {
            this["importHistorySchemaVersion"] = 0;
        }
        if (!("trackMetadataSchemaVersion" in $$source)) {
            this["trackMetadataSchemaVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildInfo($$parsedSource as Partial<BuildInfo>);
    }
}

export class DiagnosticsInfo {
    "logPath"?: string;
    "lastExportPath"?: string;
    "lastExportedAt"?: string;
    "bundleStatus"?: string;
    "bundleMessage"?: string;

    /** Creates a new DiagnosticsInfo instance. */
    constructor($$source: Partial<DiagnosticsInfo> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticsInfo($$parsedSource as Partial<DiagnosticsInfo>);
    }
}

/**
 * DuplicateMatch is a non-destructive suggestion produced from local track
 * metadata. A caller must still ask the user whether to reprocess, import
 * anyway, or replace anything; this helper never mutates or deletes files.
 */
export class DuplicateMatch {
    "trackId": string;
    "score": number;
    "reasons": string[];

    /** Creates a new DuplicateMatch instance. */
    constructor($$source: Partial<DuplicateMatch> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("reasons" in $$source)) {
            this["reasons"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DuplicateMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): DuplicateMatch {
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasons" in $$parsedSource) {
            $$parsedSource["reasons"] = $$createField2_0($$parsedSource["reasons"]);
        }
        return new DuplicateMatch($$parsedSource as Partial<DuplicateMatch>);
    }
}

export class FacetBucket {
    "value": string;
    "count": number;

    /** Creates a new FacetBucket instance. */
    constructor($$source: Partial<FacetBucket> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetBucket instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetBucket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetBucket($$parsedSource as Partial<FacetBucket>);
    }
}

export class ImportHistoryEntry {
    "url": string;
    "completedAt": string;

    /** Creates a new ImportHistoryEntry instance. */
    constructor($$source: Partial<ImportHistoryEntry> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportHistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportHistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportHistoryEntry($$parsedSource as Partial<ImportHistoryEntry>);
    }
}

export class Job {
    "id": string;
    "kind": string;
    "input": string;
    "sourceRoot"?: string;
    "downloadVideo"?: boolean;
    "trackId"?: string;
    "userContext"?: string;
    "parentJobId"?: string;
    "playlistUrl"?: string;
    "playlistTitle"?: string;
    "playlistChannel"?: string;
    "playlistTotalItems"?: number;
    "playlistProcessedItems"?: number;
    "playlistFailedItems"?: number;
    "playlistIndex"?: number;
    "playlistCurrentIndex"?: number;
    "playlistCurrentTitle"?: string;
    "playlistItemTitle"?: string;
    "status": string;
    "detail": string;
    "error"?: string;
    "outputBundle"?: string;
    "stageStatuses"?: JobStageStatuses;
    "downloadProgress"?: number;
    "metadataProgress"?: number;
    "lyricsProgress"?: number;
    "resultTitle"?: string;
    "resultArtist"?: string;
    "resultAlbum"?: string;
    "createdAt": string;
    "startedAt"?: string;
    "finishedAt"?: string;

    /** Creates a new Job instance. */
    constructor($$source: Partial<Job> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     */
    static createFrom($$source: any = {}): Job {
        const $$createField22_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stageStatuses" in $$parsedSource) {
            $$parsedSource["stageStatuses"] = $$createField22_0($$parsedSource["stageStatuses"]);
        }
        return new Job($$parsedSource as Partial<Job>);
    }
}

export class JobProgressEvent {
    "jobId": string;
    "downloadProgress": number;
    "metadataProgress": number;
    "lyricsProgress": number;
    "status": string;
    "detail"?: string;
    "stageStatuses"?: JobStageStatuses;
    "parentJobId"?: string;
    "playlistTotal"?: number;
    "playlistProcessed"?: number;
    "playlistFailed"?: number;

    /** Creates a new JobProgressEvent instance. */
    constructor($$source: Partial<JobProgressEvent> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("downloadProgress" in $$source)) {
            this["downloadProgress"] = 0;
        }
        if (!("metadataProgress" in $$source)) {
            this["metadataProgress"] = 0;
        }
        if (!("lyricsProgress" in $$source)) {
            this["lyricsProgress"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): JobProgressEvent {
        const $$createField6_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stageStatuses" in $$parsedSource) {
            $$parsedSource["stageStatuses"] = $$createField6_0($$parsedSource["stageStatuses"]);
        }
        return new JobProgressEvent($$parsedSource as Partial<JobProgressEvent>);
    }
}

export class JobStageStatuses {
    "download"?: string;
    "metadata"?: string;
    "musicBrainz"?: string;
    "lyrics"?: string;
    "artwork"?: string;
    "video"?: string;
    "finalize"?: string;

    /** Creates a new JobStageStatuses instance. */
    constructor($$source: Partial<JobStageStatuses> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobStageStatuses instance from a string or object.
     */
    static createFrom($$source: any = {}): JobStageStatuses {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobStageStatuses($$parsedSource as Partial<JobStageStatuses>);
    }
}

export class LibraryHealth {
    "totalTracks": number;
    "readyTracks": number;
    "unprocessedTracks": number;
    "missingAudio": number;
    "missingLyrics": number;
    "missingTimed": number;
    "missingMetadata": number;

    /** Creates a new LibraryHealth instance. */
    constructor($$source: Partial<LibraryHealth> = {}) {
        if (!("totalTracks" in $$source)) {
            this["totalTracks"] = 0;
        }
        if (!("readyTracks" in $$source)) {
            this["readyTracks"] = 0;
        }
        if (!("unprocessedTracks" in $$source)) {
            this["unprocessedTracks"] = 0;
        }
        if (!("missingAudio" in $$source)) {
            this["missingAudio"] = 0;
        }
        if (!("missingLyrics" in $$source)) {
            this["missingLyrics"] = 0;
        }
        if (!("missingTimed" in $$source)) {
            this["missingTimed"] = 0;
        }
        if (!("missingMetadata" in $$source)) {
            this["missingMetadata"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryHealth($$parsedSource as Partial<LibraryHealth>);
    }
}

/**
 * LibraryHealthIssue is a read-only, explainable finding. Scanning never
 * writes metadata, moves files, or queues work; a later confirmation flow can
 * decide whether a proposed fix is appropriate.
 */
export class LibraryHealthIssue {
    "id": string;
    "kind": string;
    "trackId"?: string;
    "relatedTrackId"?: string;
    "title"?: string;
    "severity": string;
    "confidence": string;
    "evidence": string[];
    "affectedPaths": string[];
    "proposedFix": string;

    /** Creates a new LibraryHealthIssue instance. */
    constructor($$source: Partial<LibraryHealthIssue> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("affectedPaths" in $$source)) {
            this["affectedPaths"] = [];
        }
        if (!("proposedFix" in $$source)) {
            this["proposedFix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryHealthIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryHealthIssue {
        const $$createField7_0 = $$createType24;
        const $$createField8_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField7_0($$parsedSource["evidence"]);
        }
        if ("affectedPaths" in $$parsedSource) {
            $$parsedSource["affectedPaths"] = $$createField8_0($$parsedSource["affectedPaths"]);
        }
        return new LibraryHealthIssue($$parsedSource as Partial<LibraryHealthIssue>);
    }
}

export class LibraryHealthReport {
    "version": string;
    "issues": LibraryHealthIssue[];

    /** Creates a new LibraryHealthReport instance. */
    constructor($$source: Partial<LibraryHealthReport> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryHealthReport instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryHealthReport {
        const $$createField1_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new LibraryHealthReport($$parsedSource as Partial<LibraryHealthReport>);
    }
}

/**
 * LibraryManifest is the portable, metadata-only representation used by local
 * backup/restore and future sync code. It deliberately does not embed
 * TrackRecord or PublicSettings: those types contain media URLs, local tool
 * paths, and fields that must never cross an export boundary.
 */
export class LibraryManifest {
    "format": string;
    "schemaVersion": number;
    "exportedAt": string;
    "manifestChecksum": string;
    "exclusions": LibraryManifestExclusions;
    "tracks": LibraryManifestTrack[];
    "playlists": LibraryManifestPlaylist[];
    "ratings"?: LibraryManifestRating[];
    "favorites"?: string[];
    "history"?: LibraryManifestHistoryEntry[];
    "settings": LibraryManifestSettings;
    "profileNotes"?: { [_ in string]?: string };

    /** Creates a new LibraryManifest instance. */
    constructor($$source: Partial<LibraryManifest> = {}) {
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("exportedAt" in $$source)) {
            this["exportedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("manifestChecksum" in $$source)) {
            this["manifestChecksum"] = "";
        }
        if (!("exclusions" in $$source)) {
            this["exclusions"] = (new LibraryManifestExclusions());
        }
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }
        if (!("playlists" in $$source)) {
            this["playlists"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new LibraryManifestSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifest {
        const $$createField4_0 = $$createType28;
        const $$createField5_0 = $$createType30;
        const $$createField6_0 = $$createType32;
        const $$createField7_0 = $$createType34;
        const $$createField8_0 = $$createType24;
        const $$createField9_0 = $$createType36;
        const $$createField10_0 = $$createType37;
        const $$createField11_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exclusions" in $$parsedSource) {
            $$parsedSource["exclusions"] = $$createField4_0($$parsedSource["exclusions"]);
        }
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField5_0($$parsedSource["tracks"]);
        }
        if ("playlists" in $$parsedSource) {
            $$parsedSource["playlists"] = $$createField6_0($$parsedSource["playlists"]);
        }
        if ("ratings" in $$parsedSource) {
            $$parsedSource["ratings"] = $$createField7_0($$parsedSource["ratings"]);
        }
        if ("favorites" in $$parsedSource) {
            $$parsedSource["favorites"] = $$createField8_0($$parsedSource["favorites"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField9_0($$parsedSource["history"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField10_0($$parsedSource["settings"]);
        }
        if ("profileNotes" in $$parsedSource) {
            $$parsedSource["profileNotes"] = $$createField11_0($$parsedSource["profileNotes"]);
        }
        return new LibraryManifest($$parsedSource as Partial<LibraryManifest>);
    }
}

export class LibraryManifestArtworkReference {
    "path"?: LibraryManifestPathReference;
    "source"?: string;
    "releaseId"?: string;
    "releaseGroupId"?: string;
    "url"?: string;
    "fetchedAt"?: string;

    /** Creates a new LibraryManifestArtworkReference instance. */
    constructor($$source: Partial<LibraryManifestArtworkReference> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestArtworkReference instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestArtworkReference {
        const $$createField0_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField0_0($$parsedSource["path"]);
        }
        return new LibraryManifestArtworkReference($$parsedSource as Partial<LibraryManifestArtworkReference>);
    }
}

/**
 * LibraryManifestExclusions is serialized as part of every manifest so a
 * consumer can verify the privacy contract without relying on documentation.
 * The booleans are intentionally not configurable by callers.
 */
export class LibraryManifestExclusions {
    "apiKeysExcluded": boolean;
    "secretsExcluded": boolean;
    "mediaBinariesExcluded": boolean;
    "lyricsTextExcluded": boolean;
    "artworkBytesExcluded": boolean;
    "excludedFields": string[];

    /** Creates a new LibraryManifestExclusions instance. */
    constructor($$source: Partial<LibraryManifestExclusions> = {}) {
        if (!("apiKeysExcluded" in $$source)) {
            this["apiKeysExcluded"] = false;
        }
        if (!("secretsExcluded" in $$source)) {
            this["secretsExcluded"] = false;
        }
        if (!("mediaBinariesExcluded" in $$source)) {
            this["mediaBinariesExcluded"] = false;
        }
        if (!("lyricsTextExcluded" in $$source)) {
            this["lyricsTextExcluded"] = false;
        }
        if (!("artworkBytesExcluded" in $$source)) {
            this["artworkBytesExcluded"] = false;
        }
        if (!("excludedFields" in $$source)) {
            this["excludedFields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestExclusions instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestExclusions {
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("excludedFields" in $$parsedSource) {
            $$parsedSource["excludedFields"] = $$createField5_0($$parsedSource["excludedFields"]);
        }
        return new LibraryManifestExclusions($$parsedSource as Partial<LibraryManifestExclusions>);
    }
}

export class LibraryManifestHistoryEntry {
    "url"?: string;
    "completedAt": string;

    /** Creates a new LibraryManifestHistoryEntry instance. */
    constructor($$source: Partial<LibraryManifestHistoryEntry> = {}) {
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestHistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestHistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryManifestHistoryEntry($$parsedSource as Partial<LibraryManifestHistoryEntry>);
    }
}

export class LibraryManifestLyricsReference {
    "path"?: LibraryManifestPathReference;
    "available": boolean;
    "timedAvailable": boolean;
    "confidence"?: string;
    "timedConfidence"?: string;
    "timedGranularity"?: string;
    "source"?: string;
    "sourceLocation"?: string;

    /** Creates a new LibraryManifestLyricsReference instance. */
    constructor($$source: Partial<LibraryManifestLyricsReference> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("timedAvailable" in $$source)) {
            this["timedAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestLyricsReference instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestLyricsReference {
        const $$createField0_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField0_0($$parsedSource["path"]);
        }
        return new LibraryManifestLyricsReference($$parsedSource as Partial<LibraryManifestLyricsReference>);
    }
}

/**
 * LibraryManifestPathReference contains a relative reference only. It never
 * contains file bytes. External paths are represented by a digest so an
 * export cannot leak an absolute path while still allowing import to report a
 * deterministic remapping problem.
 */
export class LibraryManifestPathReference {
    "relativePath"?: string;
    "external"?: boolean;
    "pathDigest"?: string;

    /** Creates a new LibraryManifestPathReference instance. */
    constructor($$source: Partial<LibraryManifestPathReference> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestPathReference instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestPathReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryManifestPathReference($$parsedSource as Partial<LibraryManifestPathReference>);
    }
}

export class LibraryManifestPlaylist {
    "id": string;
    "name": string;
    "description"?: string;
    "createdAt": string;
    "updatedAt": string;
    "trackIds": string[];

    /** Creates a new LibraryManifestPlaylist instance. */
    constructor($$source: Partial<LibraryManifestPlaylist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("trackIds" in $$source)) {
            this["trackIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestPlaylist instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestPlaylist {
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trackIds" in $$parsedSource) {
            $$parsedSource["trackIds"] = $$createField5_0($$parsedSource["trackIds"]);
        }
        return new LibraryManifestPlaylist($$parsedSource as Partial<LibraryManifestPlaylist>);
    }
}

export class LibraryManifestProvenance {
    "sourceKind"?: string;
    "sourceRef"?: string;
    "sourceUrl"?: string;
    "sourceTitle"?: string;
    "sourceChannel"?: string;
    "sources"?: string[];
    "metadataConfidence"?: string;
    "enrichmentConfidence"?: string;
    "aiProvider"?: string;
    "aiModel"?: string;
    "aiRan"?: boolean;
    "generatedAt"?: string;

    /** Creates a new LibraryManifestProvenance instance. */
    constructor($$source: Partial<LibraryManifestProvenance> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestProvenance instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestProvenance {
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField5_0($$parsedSource["sources"]);
        }
        return new LibraryManifestProvenance($$parsedSource as Partial<LibraryManifestProvenance>);
    }
}

export class LibraryManifestRating {
    "trackId": string;
    "rating": number;

    /** Creates a new LibraryManifestRating instance. */
    constructor($$source: Partial<LibraryManifestRating> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = "";
        }
        if (!("rating" in $$source)) {
            this["rating"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestRating instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestRating {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryManifestRating($$parsedSource as Partial<LibraryManifestRating>);
    }
}

export class LibraryManifestSettings {
    "provider"?: string;
    "aiModel"?: string;
    "downloadMusicVideo": boolean;
    "keepOriginalAudio": boolean;
    "maxConcurrentDownloads"?: number;
    "maxConcurrentVideoDownloads"?: number;
    "maxConcurrentEnrichmentRequests"?: number;
    "maxConcurrentLyricsRequests"?: number;
    "throttleOnYtdlpBotErrors": boolean;

    /** Creates a new LibraryManifestSettings instance. */
    constructor($$source: Partial<LibraryManifestSettings> = {}) {
        if (!("downloadMusicVideo" in $$source)) {
            this["downloadMusicVideo"] = false;
        }
        if (!("keepOriginalAudio" in $$source)) {
            this["keepOriginalAudio"] = false;
        }
        if (!("throttleOnYtdlpBotErrors" in $$source)) {
            this["throttleOnYtdlpBotErrors"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryManifestSettings($$parsedSource as Partial<LibraryManifestSettings>);
    }
}

export class LibraryManifestTrack {
    "id": string;
    "metadata": LibraryManifestTrackMetadata;
    "paths": LibraryManifestTrackPaths;
    "lyrics": LibraryManifestLyricsReference;
    "artwork": LibraryManifestArtworkReference;
    "provenance": LibraryManifestProvenance;

    /** Creates a new LibraryManifestTrack instance. */
    constructor($$source: Partial<LibraryManifestTrack> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = (new LibraryManifestTrackMetadata());
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new LibraryManifestTrackPaths());
        }
        if (!("lyrics" in $$source)) {
            this["lyrics"] = (new LibraryManifestLyricsReference());
        }
        if (!("artwork" in $$source)) {
            this["artwork"] = (new LibraryManifestArtworkReference());
        }
        if (!("provenance" in $$source)) {
            this["provenance"] = (new LibraryManifestProvenance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestTrack {
        const $$createField1_0 = $$createType40;
        const $$createField2_0 = $$createType41;
        const $$createField3_0 = $$createType42;
        const $$createField4_0 = $$createType43;
        const $$createField5_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField1_0($$parsedSource["metadata"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField2_0($$parsedSource["paths"]);
        }
        if ("lyrics" in $$parsedSource) {
            $$parsedSource["lyrics"] = $$createField3_0($$parsedSource["lyrics"]);
        }
        if ("artwork" in $$parsedSource) {
            $$parsedSource["artwork"] = $$createField4_0($$parsedSource["artwork"]);
        }
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField5_0($$parsedSource["provenance"]);
        }
        return new LibraryManifestTrack($$parsedSource as Partial<LibraryManifestTrack>);
    }
}

export class LibraryManifestTrackMetadata {
    "title": string;
    "artist": string;
    "album": string;
    "genre": string;
    "year"?: string;
    "durationSeconds"?: number | null;
    "confidence"?: string;
    "metadataConfidence"?: string;
    "enrichmentConfidence"?: string;
    "releaseType"?: string;
    "isrc"?: string;
    "artistLinks"?: MetadataLinks;
    "albumLinks"?: MetadataLinks;
    "songLinks"?: MetadataLinks;
    "artistTrivia"?: string[];
    "albumTrivia"?: string[];
    "songTrivia"?: string[];
    "songMeaning"?: string;
    "tidbits"?: string[];
    "sources"?: string[];
    "notes"?: string;

    /** Creates a new LibraryManifestTrackMetadata instance. */
    constructor($$source: Partial<LibraryManifestTrackMetadata> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("genre" in $$source)) {
            this["genre"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestTrackMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestTrackMetadata {
        const $$createField11_0 = $$createType45;
        const $$createField12_0 = $$createType45;
        const $$createField13_0 = $$createType45;
        const $$createField14_0 = $$createType24;
        const $$createField15_0 = $$createType24;
        const $$createField16_0 = $$createType24;
        const $$createField18_0 = $$createType24;
        const $$createField19_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artistLinks" in $$parsedSource) {
            $$parsedSource["artistLinks"] = $$createField11_0($$parsedSource["artistLinks"]);
        }
        if ("albumLinks" in $$parsedSource) {
            $$parsedSource["albumLinks"] = $$createField12_0($$parsedSource["albumLinks"]);
        }
        if ("songLinks" in $$parsedSource) {
            $$parsedSource["songLinks"] = $$createField13_0($$parsedSource["songLinks"]);
        }
        if ("artistTrivia" in $$parsedSource) {
            $$parsedSource["artistTrivia"] = $$createField14_0($$parsedSource["artistTrivia"]);
        }
        if ("albumTrivia" in $$parsedSource) {
            $$parsedSource["albumTrivia"] = $$createField15_0($$parsedSource["albumTrivia"]);
        }
        if ("songTrivia" in $$parsedSource) {
            $$parsedSource["songTrivia"] = $$createField16_0($$parsedSource["songTrivia"]);
        }
        if ("tidbits" in $$parsedSource) {
            $$parsedSource["tidbits"] = $$createField18_0($$parsedSource["tidbits"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField19_0($$parsedSource["sources"]);
        }
        return new LibraryManifestTrackMetadata($$parsedSource as Partial<LibraryManifestTrackMetadata>);
    }
}

export class LibraryManifestTrackPaths {
    "metadata": LibraryManifestPathReference;
    "storageDir"?: LibraryManifestPathReference;
    "bundle"?: LibraryManifestPathReference;
    "audio"?: LibraryManifestPathReference;
    "timedLyrics"?: LibraryManifestPathReference;
    "video"?: LibraryManifestPathReference;

    /** Creates a new LibraryManifestTrackPaths instance. */
    constructor($$source: Partial<LibraryManifestTrackPaths> = {}) {
        if (!("metadata" in $$source)) {
            this["metadata"] = (new LibraryManifestPathReference());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryManifestTrackPaths instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryManifestTrackPaths {
        const $$createField0_0 = $$createType39;
        const $$createField1_0 = $$createType39;
        const $$createField2_0 = $$createType39;
        const $$createField3_0 = $$createType39;
        const $$createField4_0 = $$createType39;
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField0_0($$parsedSource["metadata"]);
        }
        if ("storageDir" in $$parsedSource) {
            $$parsedSource["storageDir"] = $$createField1_0($$parsedSource["storageDir"]);
        }
        if ("bundle" in $$parsedSource) {
            $$parsedSource["bundle"] = $$createField2_0($$parsedSource["bundle"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField3_0($$parsedSource["audio"]);
        }
        if ("timedLyrics" in $$parsedSource) {
            $$parsedSource["timedLyrics"] = $$createField4_0($$parsedSource["timedLyrics"]);
        }
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField5_0($$parsedSource["video"]);
        }
        return new LibraryManifestTrackPaths($$parsedSource as Partial<LibraryManifestTrackPaths>);
    }
}

export class LibraryStats {
    "trackCount": number;
    "artistCount": number;
    "albumCount": number;
    "jobCount": number;
    "pendingJobs": number;
    "failedJobs": number;

    /** Creates a new LibraryStats instance. */
    constructor($$source: Partial<LibraryStats> = {}) {
        if (!("trackCount" in $$source)) {
            this["trackCount"] = 0;
        }
        if (!("artistCount" in $$source)) {
            this["artistCount"] = 0;
        }
        if (!("albumCount" in $$source)) {
            this["albumCount"] = 0;
        }
        if (!("jobCount" in $$source)) {
            this["jobCount"] = 0;
        }
        if (!("pendingJobs" in $$source)) {
            this["pendingJobs"] = 0;
        }
        if (!("failedJobs" in $$source)) {
            this["failedJobs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryStats instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryStats($$parsedSource as Partial<LibraryStats>);
    }
}

export class MediaFileInfo {
    "url": string;
    "mimeType": string;
    "reachable": boolean;
    "statusCode": number;
    "contentLength": number;
    "expiresAt"?: string;

    /** Creates a new MediaFileInfo instance. */
    constructor($$source: Partial<MediaFileInfo> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("contentLength" in $$source)) {
            this["contentLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaFileInfo($$parsedSource as Partial<MediaFileInfo>);
    }
}

export class MetadataLinks {
    "officialWebsite"?: string;
    "spotify"?: string;
    "appleMusic"?: string;
    "youtube"?: string;
    "youtubeMusic"?: string;
    "instagram"?: string;
    "x"?: string;
    "facebook"?: string;
    "bandcamp"?: string;
    "soundcloud"?: string;
    "wikipedia"?: string;
    "musicBrainz"?: string;
    "genius"?: string;

    /** Creates a new MetadataLinks instance. */
    constructor($$source: Partial<MetadataLinks> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataLinks instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataLinks {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataLinks($$parsedSource as Partial<MetadataLinks>);
    }
}

export class PlaybackState {
    "currentTrackId": string;
    "currentTrackPath": string;
    "queue": string[];
    "queueSource": string;
    "isPlaying": boolean;
    "isLoading": boolean;
    "currentTime": number;
    "duration": number;
    "volume": number;
    "muted": boolean;
    "shuffleEnabled": boolean;
    "repeatMode": string;
    "error": string;

    /** Creates a new PlaybackState instance. */
    constructor($$source: Partial<PlaybackState> = {}) {
        if (!("currentTrackId" in $$source)) {
            this["currentTrackId"] = "";
        }
        if (!("currentTrackPath" in $$source)) {
            this["currentTrackPath"] = "";
        }
        if (!("queue" in $$source)) {
            this["queue"] = [];
        }
        if (!("queueSource" in $$source)) {
            this["queueSource"] = "";
        }
        if (!("isPlaying" in $$source)) {
            this["isPlaying"] = false;
        }
        if (!("isLoading" in $$source)) {
            this["isLoading"] = false;
        }
        if (!("currentTime" in $$source)) {
            this["currentTime"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("muted" in $$source)) {
            this["muted"] = false;
        }
        if (!("shuffleEnabled" in $$source)) {
            this["shuffleEnabled"] = false;
        }
        if (!("repeatMode" in $$source)) {
            this["repeatMode"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackState instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackState {
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("queue" in $$parsedSource) {
            $$parsedSource["queue"] = $$createField2_0($$parsedSource["queue"]);
        }
        return new PlaybackState($$parsedSource as Partial<PlaybackState>);
    }
}

export class Playlist {
    "id": string;
    "name": string;
    "description": string;
    "createdAt": string;
    "updatedAt": string;
    "trackIds": string[];

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("trackIds" in $$source)) {
            this["trackIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trackIds" in $$parsedSource) {
            $$parsedSource["trackIds"] = $$createField5_0($$parsedSource["trackIds"]);
        }
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

export class PromptInfo {
    "name": string;
    "purpose": string;

    /** Creates a new PromptInfo instance. */
    constructor($$source: Partial<PromptInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("purpose" in $$source)) {
            this["purpose"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptInfo($$parsedSource as Partial<PromptInfo>);
    }
}

export class PublicSettings {
    "libraryRoot": string;
    "aiBaseUrl": string;
    "aiModel": string;
    "provider": string;
    "apiKeyConfigured": boolean;
    "updateManifestUrl"?: string;
    "ytDlpPath": string;
    "ffmpegPath": string;
    "ytDlpCookiesPath": string;
    "ytDlpCookiesFromBrowser": string;
    "videoDownloadMode": string;
    "downloadMusicVideo": boolean;
    "keepOriginalAudio": boolean;
    "maxConcurrentDownloads": number;
    "maxConcurrentVideoDownloads": number;
    "maxConcurrentEnrichmentRequests": number;
    "maxConcurrentLyricsRequests": number;
    "throttleOnYtdlpBotErrors": boolean;

    /** Creates a new PublicSettings instance. */
    constructor($$source: Partial<PublicSettings> = {}) {
        if (!("libraryRoot" in $$source)) {
            this["libraryRoot"] = "";
        }
        if (!("aiBaseUrl" in $$source)) {
            this["aiBaseUrl"] = "";
        }
        if (!("aiModel" in $$source)) {
            this["aiModel"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("apiKeyConfigured" in $$source)) {
            this["apiKeyConfigured"] = false;
        }
        if (!("ytDlpPath" in $$source)) {
            this["ytDlpPath"] = "";
        }
        if (!("ffmpegPath" in $$source)) {
            this["ffmpegPath"] = "";
        }
        if (!("ytDlpCookiesPath" in $$source)) {
            this["ytDlpCookiesPath"] = "";
        }
        if (!("ytDlpCookiesFromBrowser" in $$source)) {
            this["ytDlpCookiesFromBrowser"] = "";
        }
        if (!("videoDownloadMode" in $$source)) {
            this["videoDownloadMode"] = "";
        }
        if (!("downloadMusicVideo" in $$source)) {
            this["downloadMusicVideo"] = false;
        }
        if (!("keepOriginalAudio" in $$source)) {
            this["keepOriginalAudio"] = false;
        }
        if (!("maxConcurrentDownloads" in $$source)) {
            this["maxConcurrentDownloads"] = 0;
        }
        if (!("maxConcurrentVideoDownloads" in $$source)) {
            this["maxConcurrentVideoDownloads"] = 0;
        }
        if (!("maxConcurrentEnrichmentRequests" in $$source)) {
            this["maxConcurrentEnrichmentRequests"] = 0;
        }
        if (!("maxConcurrentLyricsRequests" in $$source)) {
            this["maxConcurrentLyricsRequests"] = 0;
        }
        if (!("throttleOnYtdlpBotErrors" in $$source)) {
            this["throttleOnYtdlpBotErrors"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicSettings($$parsedSource as Partial<PublicSettings>);
    }
}

export class RootInfo {
    "libraryRoot": string;
    "appDataDir": string;
    "incomingDir": string;
    "libraryDir": string;
    "cacheDir": string;

    /** Creates a new RootInfo instance. */
    constructor($$source: Partial<RootInfo> = {}) {
        if (!("libraryRoot" in $$source)) {
            this["libraryRoot"] = "";
        }
        if (!("appDataDir" in $$source)) {
            this["appDataDir"] = "";
        }
        if (!("incomingDir" in $$source)) {
            this["incomingDir"] = "";
        }
        if (!("libraryDir" in $$source)) {
            this["libraryDir"] = "";
        }
        if (!("cacheDir" in $$source)) {
            this["cacheDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RootInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RootInfo($$parsedSource as Partial<RootInfo>);
    }
}

export class SettingsInput {
    "libraryRoot": string;
    "aiBaseUrl": string;
    "aiModel": string;
    "provider": string;
    "apiKey": string;
    "updateManifestUrl": string;
    "ytDlpPath": string;
    "ffmpegPath": string;
    "ytDlpCookiesPath": string;
    "ytDlpCookiesFromBrowser": string;
    "videoDownloadMode": string;
    "downloadMusicVideo": boolean;
    "keepOriginalAudio": boolean;
    "maxConcurrentDownloads": number;
    "maxConcurrentVideoDownloads": number;
    "maxConcurrentEnrichmentRequests": number;
    "maxConcurrentLyricsRequests": number;
    "throttleOnYtdlpBotErrors": boolean;

    /** Creates a new SettingsInput instance. */
    constructor($$source: Partial<SettingsInput> = {}) {
        if (!("libraryRoot" in $$source)) {
            this["libraryRoot"] = "";
        }
        if (!("aiBaseUrl" in $$source)) {
            this["aiBaseUrl"] = "";
        }
        if (!("aiModel" in $$source)) {
            this["aiModel"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("updateManifestUrl" in $$source)) {
            this["updateManifestUrl"] = "";
        }
        if (!("ytDlpPath" in $$source)) {
            this["ytDlpPath"] = "";
        }
        if (!("ffmpegPath" in $$source)) {
            this["ffmpegPath"] = "";
        }
        if (!("ytDlpCookiesPath" in $$source)) {
            this["ytDlpCookiesPath"] = "";
        }
        if (!("ytDlpCookiesFromBrowser" in $$source)) {
            this["ytDlpCookiesFromBrowser"] = "";
        }
        if (!("videoDownloadMode" in $$source)) {
            this["videoDownloadMode"] = "";
        }
        if (!("downloadMusicVideo" in $$source)) {
            this["downloadMusicVideo"] = false;
        }
        if (!("keepOriginalAudio" in $$source)) {
            this["keepOriginalAudio"] = false;
        }
        if (!("maxConcurrentDownloads" in $$source)) {
            this["maxConcurrentDownloads"] = 0;
        }
        if (!("maxConcurrentVideoDownloads" in $$source)) {
            this["maxConcurrentVideoDownloads"] = 0;
        }
        if (!("maxConcurrentEnrichmentRequests" in $$source)) {
            this["maxConcurrentEnrichmentRequests"] = 0;
        }
        if (!("maxConcurrentLyricsRequests" in $$source)) {
            this["maxConcurrentLyricsRequests"] = 0;
        }
        if (!("throttleOnYtdlpBotErrors" in $$source)) {
            this["throttleOnYtdlpBotErrors"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput($$parsedSource as Partial<SettingsInput>);
    }
}

/**
 * SmartPlaylistDefinition is the versioned, serializable definition of a
 * generated playlist. ID is the stable identity used by the resulting
 * Playlist; it must be supplied by the caller rather than generated from
 * mutable track data.
 */
export class SmartPlaylistDefinition {
    "schemaVersion": number;
    "id": string;
    "name": string;
    "description"?: string;
    "rule": SmartPlaylistRule;
    "sort"?: SmartPlaylistSort;
    "limit"?: number;

    /** Creates a new SmartPlaylistDefinition instance. */
    constructor($$source: Partial<SmartPlaylistDefinition> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rule" in $$source)) {
            this["rule"] = (new SmartPlaylistRule());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistDefinition {
        const $$createField4_0 = $$createType46;
        const $$createField5_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rule" in $$parsedSource) {
            $$parsedSource["rule"] = $$createField4_0($$parsedSource["rule"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField5_0($$parsedSource["sort"]);
        }
        return new SmartPlaylistDefinition($$parsedSource as Partial<SmartPlaylistDefinition>);
    }
}

/**
 * SmartPlaylistEvaluation is the offline result of evaluating a definition.
 * TotalMatches is reported before Limit is applied, allowing a preview to
 * display both the full count and the generated Playlist contents.
 */
export class SmartPlaylistEvaluation {
    "playlist": Playlist;
    "matches": SmartPlaylistMatch[];
    "totalMatches": number;

    /** Creates a new SmartPlaylistEvaluation instance. */
    constructor($$source: Partial<SmartPlaylistEvaluation> = {}) {
        if (!("playlist" in $$source)) {
            this["playlist"] = (new Playlist());
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }
        if (!("totalMatches" in $$source)) {
            this["totalMatches"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistEvaluation instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistEvaluation {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playlist" in $$parsedSource) {
            $$parsedSource["playlist"] = $$createField0_0($$parsedSource["playlist"]);
        }
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SmartPlaylistEvaluation($$parsedSource as Partial<SmartPlaylistEvaluation>);
    }
}

/**
 * SmartPlaylistExplanation is a tree mirroring the rule. Leaf nodes contain
 * the normalized actual value, expected value, and a short human-readable
 * reason; group nodes retain their child explanations for explainability.
 */
export class SmartPlaylistExplanation {
    "matched": boolean;
    "kind": string;
    "field"?: SmartPlaylistField;
    "operator"?: SmartPlaylistOperator;
    "expected"?: string;
    "actual"?: string;
    "reason": string;
    "children"?: SmartPlaylistExplanation[];

    /** Creates a new SmartPlaylistExplanation instance. */
    constructor($$source: Partial<SmartPlaylistExplanation> = {}) {
        if (!("matched" in $$source)) {
            this["matched"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistExplanation instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistExplanation {
        const $$createField7_0 = $$createType51;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new SmartPlaylistExplanation($$parsedSource as Partial<SmartPlaylistExplanation>);
    }
}

/**
 * SmartPlaylistField identifies a catalog or local-history value that can be
 * queried by a smart playlist rule.
 */
export enum SmartPlaylistField {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SmartPlaylistFieldArtist = "artist",
    SmartPlaylistFieldAlbum = "album",
    SmartPlaylistFieldTitle = "title",
    SmartPlaylistFieldGenre = "genre",
    SmartPlaylistFieldMood = "mood",
    SmartPlaylistFieldYear = "year",
    SmartPlaylistFieldDecade = "decade",
    SmartPlaylistFieldCreatedAt = "createdAt",
    SmartPlaylistFieldRecentlyAdded = "recentlyAdded",
    SmartPlaylistFieldLastPlayedAt = "lastPlayedAt",
    SmartPlaylistFieldRecentlyPlayed = "recentlyPlayed",
    SmartPlaylistFieldPlayCount = "playCount",
    SmartPlaylistFieldNeverPlayed = "neverPlayed",
    SmartPlaylistFieldConfidence = "confidence",
    SmartPlaylistFieldMetadataConfidence = "metadataConfidence",
    SmartPlaylistFieldEnrichmentConfidence = "enrichmentConfidence",
    SmartPlaylistFieldMissingMetadata = "missingMetadata",
    SmartPlaylistFieldDuplicateCandidate = "duplicateCandidate",
    SmartPlaylistFieldVersion = "version",
    SmartPlaylistFieldIncompleteAlbum = "incompleteAlbum",
    SmartPlaylistFieldHasLyrics = "hasLyrics",
    SmartPlaylistFieldHasTimedLyrics = "hasTimedLyrics",
    SmartPlaylistFieldHasArtwork = "hasArtwork",
    SmartPlaylistFieldHasVideo = "hasVideo",
    SmartPlaylistFieldDurationSeconds = "durationSeconds",
};

/**
 * SmartPlaylistMatch pairs a matching track with the explanation that can be
 * shown in a preview or saved alongside a future UI result.
 */
export class SmartPlaylistMatch {
    "track": TrackRecord;
    "context"?: SmartPlaylistTrackContext;
    "explanation": SmartPlaylistExplanation;

    /** Creates a new SmartPlaylistMatch instance. */
    constructor($$source: Partial<SmartPlaylistMatch> = {}) {
        if (!("track" in $$source)) {
            this["track"] = (new TrackRecord());
        }
        if (!("explanation" in $$source)) {
            this["explanation"] = (new SmartPlaylistExplanation());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistMatch {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType52;
        const $$createField2_0 = $$createType50;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("track" in $$parsedSource) {
            $$parsedSource["track"] = $$createField0_0($$parsedSource["track"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField1_0($$parsedSource["context"]);
        }
        if ("explanation" in $$parsedSource) {
            $$parsedSource["explanation"] = $$createField2_0($$parsedSource["explanation"]);
        }
        return new SmartPlaylistMatch($$parsedSource as Partial<SmartPlaylistMatch>);
    }
}

/**
 * SmartPlaylistOperator is the comparison performed by a leaf rule.
 */
export enum SmartPlaylistOperator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SmartPlaylistOperatorEquals = "equals",
    SmartPlaylistOperatorNotEquals = "notEquals",
    SmartPlaylistOperatorContains = "contains",
    SmartPlaylistOperatorIn = "in",
    SmartPlaylistOperatorMissing = "missing",
    SmartPlaylistOperatorNotMissing = "notMissing",
    SmartPlaylistOperatorGreaterThan = "greaterThan",
    SmartPlaylistOperatorGreaterOrEqual = "greaterOrEqual",
    SmartPlaylistOperatorLessThan = "lessThan",
    SmartPlaylistOperatorLessOrEqual = "lessOrEqual",
    SmartPlaylistOperatorBetween = "between",
    SmartPlaylistOperatorBefore = "before",
    SmartPlaylistOperatorAfter = "after",
    SmartPlaylistOperatorIsTrue = "isTrue",
    SmartPlaylistOperatorIsFalse = "isFalse",
};

/**
 * SmartPlaylistPredicate is one inspectable leaf in a SmartPlaylistRule.
 * Value is used by unary comparisons; Values is used by "in" and "between".
 * Dates use RFC3339 strings so definitions remain portable and human-editable.
 */
export class SmartPlaylistPredicate {
    "field": SmartPlaylistField;
    "operator": SmartPlaylistOperator;
    "value"?: string;
    "values"?: string[];

    /** Creates a new SmartPlaylistPredicate instance. */
    constructor($$source: Partial<SmartPlaylistPredicate> = {}) {
        if (!("field" in $$source)) {
            this["field"] = SmartPlaylistField.$zero;
        }
        if (!("operator" in $$source)) {
            this["operator"] = SmartPlaylistOperator.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistPredicate instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistPredicate {
        const $$createField3_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new SmartPlaylistPredicate($$parsedSource as Partial<SmartPlaylistPredicate>);
    }
}

/**
 * SmartPlaylistRule is a boolean expression. Exactly one of All, Any, Not,
 * or Predicate must be present at each node. This explicit recursive shape
 * keeps JSON round trips deterministic and avoids interface-based decoding.
 */
export class SmartPlaylistRule {
    "all"?: SmartPlaylistRule[];
    "any"?: SmartPlaylistRule[];
    "not"?: SmartPlaylistRule | null;
    "predicate"?: SmartPlaylistPredicate | null;

    /** Creates a new SmartPlaylistRule instance. */
    constructor($$source: Partial<SmartPlaylistRule> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistRule instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistRule {
        const $$createField0_0 = $$createType53;
        const $$createField1_0 = $$createType53;
        const $$createField2_0 = $$createType54;
        const $$createField3_0 = $$createType56;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("all" in $$parsedSource) {
            $$parsedSource["all"] = $$createField0_0($$parsedSource["all"]);
        }
        if ("any" in $$parsedSource) {
            $$parsedSource["any"] = $$createField1_0($$parsedSource["any"]);
        }
        if ("not" in $$parsedSource) {
            $$parsedSource["not"] = $$createField2_0($$parsedSource["not"]);
        }
        if ("predicate" in $$parsedSource) {
            $$parsedSource["predicate"] = $$createField3_0($$parsedSource["predicate"]);
        }
        return new SmartPlaylistRule($$parsedSource as Partial<SmartPlaylistRule>);
    }
}

/**
 * SmartPlaylistSort controls ordering. Sorting is stable: tracks with equal
 * sort values retain their input/catalog order, including in descending mode.
 */
export class SmartPlaylistSort {
    "field": SmartPlaylistSortField;
    "descending"?: boolean;

    /** Creates a new SmartPlaylistSort instance. */
    constructor($$source: Partial<SmartPlaylistSort> = {}) {
        if (!("field" in $$source)) {
            this["field"] = SmartPlaylistSortField.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistSort instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistSort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SmartPlaylistSort($$parsedSource as Partial<SmartPlaylistSort>);
    }
}

/**
 * SmartPlaylistSortField is the primary field used to order generated tracks.
 */
export enum SmartPlaylistSortField {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SmartPlaylistSortTitle = "title",
    SmartPlaylistSortArtist = "artist",
    SmartPlaylistSortAlbum = "album",
    SmartPlaylistSortGenre = "genre",
    SmartPlaylistSortYear = "year",
    SmartPlaylistSortCreatedAt = "createdAt",
    SmartPlaylistSortLastPlayedAt = "lastPlayedAt",
    SmartPlaylistSortPlayCount = "playCount",
    SmartPlaylistSortDurationSeconds = "durationSeconds",
    SmartPlaylistSortID = "id",
};

/**
 * SmartPlaylistTrackContext contains optional local facts that are not part of
 * TrackRecord. It is intentionally caller-supplied so listening history stays
 * local and opt-in; an absent context simply behaves like an unplayed track
 * with no derived facts.
 */
export class SmartPlaylistTrackContext {
    "lastPlayedAt"?: string | null;
    "playCount"?: number;
    "moods"?: string[];
    "duplicateCandidate"?: boolean;
    "versionKey"?: string;
    "albumTrackCount"?: number;
    "expectedAlbumTrackCount"?: number;

    /** Creates a new SmartPlaylistTrackContext instance. */
    constructor($$source: Partial<SmartPlaylistTrackContext> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartPlaylistTrackContext instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartPlaylistTrackContext {
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("moods" in $$parsedSource) {
            $$parsedSource["moods"] = $$createField2_0($$parsedSource["moods"]);
        }
        return new SmartPlaylistTrackContext($$parsedSource as Partial<SmartPlaylistTrackContext>);
    }
}

export const SongAIContext = songstore$0.SongAIContext;
export type SongAIContext = songstore$0.SongAIContext;

/**
 * ToolReadiness is the safe, user-facing result of the most recent external
 * tool probe. It intentionally contains no executable path or command output.
 */
export class ToolReadiness {
    "tool": string;
    "status": string;
    "version"?: string;
    "error"?: string;
    "remediation"?: string;
    "correlationId"?: string;

    /** Creates a new ToolReadiness instance. */
    constructor($$source: Partial<ToolReadiness> = {}) {
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolReadiness instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolReadiness {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolReadiness($$parsedSource as Partial<ToolReadiness>);
    }
}

export class ToolStatus {
    "ytDlp": boolean;
    "ffmpeg": boolean;
    "ai": boolean;

    /** Creates a new ToolStatus instance. */
    constructor($$source: Partial<ToolStatus> = {}) {
        if (!("ytDlp" in $$source)) {
            this["ytDlp"] = false;
        }
        if (!("ffmpeg" in $$source)) {
            this["ffmpeg"] = false;
        }
        if (!("ai" in $$source)) {
            this["ai"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolStatus($$parsedSource as Partial<ToolStatus>);
    }
}

export class TrackFileState {
    "label": string;
    "path": string;
    "exists": boolean;

    /** Creates a new TrackFileState instance. */
    constructor($$source: Partial<TrackFileState> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackFileState($$parsedSource as Partial<TrackFileState>);
    }
}

export class TrackPreview {
    "track": TrackRecord;
    "lyricsText": string;
    "timedLyricsText": string;
    "fileStates": TrackFileState[];
    "title": string;
    "artist": string;
    "album": string;
    "trackNumber"?: number | null;
    "year"?: number | null;
    "genre": string;
    "durationSeconds"?: number | null;
    "confidence"?: string;
    "metadataConfidence"?: string;
    "enrichmentConfidence"?: string;
    "releaseType"?: string;
    "isrc"?: string;
    "artistLinks"?: MetadataLinks;
    "albumLinks"?: MetadataLinks;
    "songLinks"?: MetadataLinks;
    "artistTrivia"?: string[];
    "albumTrivia"?: string[];
    "songTrivia"?: string[];
    "songMeaning"?: string;
    "tidbits"?: string[];
    "sources"?: string[];
    "metadataNotes"?: string;
    "sourceUrl": string;
    "sourceProvider": string;
    "sourceVideoId": string;
    "sourceTitle": string;
    "sourceChannel": string;
    "aiProvider": string;
    "aiModel": string;
    "aiRan": boolean;
    "aiStatus"?: string;
    "aiMessage"?: string;
    "aiContext"?: SongAIContext;
    "generatedAt": string;
    "lyricsConfidence"?: string;
    "lyricsSource"?: string;
    "lyricsSourceLoc"?: string;
    "timedLyricsConfidence"?: string;
    "timedLyricsSource"?: string;
    "timedLyricsGranularity"?: string;
    "artworkPath"?: string;
    "artworkDataUrl"?: string;
    "artworkMediaUrl"?: string;
    "videoPath"?: string;
    "videoUrl"?: string;

    /** Creates a new TrackPreview instance. */
    constructor($$source: Partial<TrackPreview> = {}) {
        if (!("track" in $$source)) {
            this["track"] = (new TrackRecord());
        }
        if (!("lyricsText" in $$source)) {
            this["lyricsText"] = "";
        }
        if (!("timedLyricsText" in $$source)) {
            this["timedLyricsText"] = "";
        }
        if (!("fileStates" in $$source)) {
            this["fileStates"] = [];
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("genre" in $$source)) {
            this["genre"] = "";
        }
        if (!("sourceUrl" in $$source)) {
            this["sourceUrl"] = "";
        }
        if (!("sourceProvider" in $$source)) {
            this["sourceProvider"] = "";
        }
        if (!("sourceVideoId" in $$source)) {
            this["sourceVideoId"] = "";
        }
        if (!("sourceTitle" in $$source)) {
            this["sourceTitle"] = "";
        }
        if (!("sourceChannel" in $$source)) {
            this["sourceChannel"] = "";
        }
        if (!("aiProvider" in $$source)) {
            this["aiProvider"] = "";
        }
        if (!("aiModel" in $$source)) {
            this["aiModel"] = "";
        }
        if (!("aiRan" in $$source)) {
            this["aiRan"] = false;
        }
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackPreview {
        const $$createField0_0 = $$createType13;
        const $$createField3_0 = $$createType58;
        const $$createField16_0 = $$createType45;
        const $$createField17_0 = $$createType45;
        const $$createField18_0 = $$createType45;
        const $$createField19_0 = $$createType24;
        const $$createField20_0 = $$createType24;
        const $$createField21_0 = $$createType24;
        const $$createField23_0 = $$createType24;
        const $$createField24_0 = $$createType24;
        const $$createField36_0 = $$createType59;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("track" in $$parsedSource) {
            $$parsedSource["track"] = $$createField0_0($$parsedSource["track"]);
        }
        if ("fileStates" in $$parsedSource) {
            $$parsedSource["fileStates"] = $$createField3_0($$parsedSource["fileStates"]);
        }
        if ("artistLinks" in $$parsedSource) {
            $$parsedSource["artistLinks"] = $$createField16_0($$parsedSource["artistLinks"]);
        }
        if ("albumLinks" in $$parsedSource) {
            $$parsedSource["albumLinks"] = $$createField17_0($$parsedSource["albumLinks"]);
        }
        if ("songLinks" in $$parsedSource) {
            $$parsedSource["songLinks"] = $$createField18_0($$parsedSource["songLinks"]);
        }
        if ("artistTrivia" in $$parsedSource) {
            $$parsedSource["artistTrivia"] = $$createField19_0($$parsedSource["artistTrivia"]);
        }
        if ("albumTrivia" in $$parsedSource) {
            $$parsedSource["albumTrivia"] = $$createField20_0($$parsedSource["albumTrivia"]);
        }
        if ("songTrivia" in $$parsedSource) {
            $$parsedSource["songTrivia"] = $$createField21_0($$parsedSource["songTrivia"]);
        }
        if ("tidbits" in $$parsedSource) {
            $$parsedSource["tidbits"] = $$createField23_0($$parsedSource["tidbits"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField24_0($$parsedSource["sources"]);
        }
        if ("aiContext" in $$parsedSource) {
            $$parsedSource["aiContext"] = $$createField36_0($$parsedSource["aiContext"]);
        }
        return new TrackPreview($$parsedSource as Partial<TrackPreview>);
    }
}

export class TrackRecord {
    "id": string;
    "artist": string;
    "album": string;
    "title": string;
    "genre": string;
    "year": string;
    "lyricsIncluded": boolean;
    "confidence"?: string;
    "bundlePath": string;
    "storageDir": string;
    "audioPath": string;
    "lyricsPath": string;
    "lrcPath": string;
    "artworkPath": string;
    "videoPath": string;
    "artworkDataUrl"?: string;
    "artworkMediaUrl"?: string;
    "artworkUrl"?: string;
    "videoUrl"?: string;
    "metadataPath": string;
    "metadataConfidence"?: string;
    "enrichmentConfidence"?: string;
    "releaseType"?: string;
    "isrc"?: string;
    "artistLinks"?: MetadataLinks;
    "albumLinks"?: MetadataLinks;
    "songLinks"?: MetadataLinks;
    "artistTrivia"?: string[];
    "albumTrivia"?: string[];
    "songTrivia"?: string[];
    "songMeaning"?: string;
    "tidbits"?: string[];
    "sources"?: string[];
    "metadataNotes"?: string;
    "lyricsConfidence"?: string;
    "lyricsSource"?: string;
    "lyricsSourceLoc"?: string;
    "timedLyricsConfidence"?: string;
    "timedLyricsGranularity"?: string;
    "hasTimedLyrics": boolean;
    "sourceTitle"?: string;
    "sourceChannel"?: string;
    "aiProvider"?: string;
    "aiModel"?: string;
    "aiRan"?: boolean;
    "aiStatus"?: string;
    "aiMessage"?: string;
    "aiContext"?: SongAIContext;
    "generatedAt"?: string;
    "sourceKind": string;
    "sourceRef": string;
    "durationSeconds"?: number | null;
    "metadataSize"?: number;
    "metadataModTime"?: string;
    "hash": string;
    "createdAt": string;

    /** Creates a new TrackRecord instance. */
    constructor($$source: Partial<TrackRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("genre" in $$source)) {
            this["genre"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = "";
        }
        if (!("lyricsIncluded" in $$source)) {
            this["lyricsIncluded"] = false;
        }
        if (!("bundlePath" in $$source)) {
            this["bundlePath"] = "";
        }
        if (!("storageDir" in $$source)) {
            this["storageDir"] = "";
        }
        if (!("audioPath" in $$source)) {
            this["audioPath"] = "";
        }
        if (!("lyricsPath" in $$source)) {
            this["lyricsPath"] = "";
        }
        if (!("lrcPath" in $$source)) {
            this["lrcPath"] = "";
        }
        if (!("artworkPath" in $$source)) {
            this["artworkPath"] = "";
        }
        if (!("videoPath" in $$source)) {
            this["videoPath"] = "";
        }
        if (!("metadataPath" in $$source)) {
            this["metadataPath"] = "";
        }
        if (!("hasTimedLyrics" in $$source)) {
            this["hasTimedLyrics"] = false;
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("sourceRef" in $$source)) {
            this["sourceRef"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackRecord {
        const $$createField24_0 = $$createType45;
        const $$createField25_0 = $$createType45;
        const $$createField26_0 = $$createType45;
        const $$createField27_0 = $$createType24;
        const $$createField28_0 = $$createType24;
        const $$createField29_0 = $$createType24;
        const $$createField31_0 = $$createType24;
        const $$createField32_0 = $$createType24;
        const $$createField47_0 = $$createType59;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artistLinks" in $$parsedSource) {
            $$parsedSource["artistLinks"] = $$createField24_0($$parsedSource["artistLinks"]);
        }
        if ("albumLinks" in $$parsedSource) {
            $$parsedSource["albumLinks"] = $$createField25_0($$parsedSource["albumLinks"]);
        }
        if ("songLinks" in $$parsedSource) {
            $$parsedSource["songLinks"] = $$createField26_0($$parsedSource["songLinks"]);
        }
        if ("artistTrivia" in $$parsedSource) {
            $$parsedSource["artistTrivia"] = $$createField27_0($$parsedSource["artistTrivia"]);
        }
        if ("albumTrivia" in $$parsedSource) {
            $$parsedSource["albumTrivia"] = $$createField28_0($$parsedSource["albumTrivia"]);
        }
        if ("songTrivia" in $$parsedSource) {
            $$parsedSource["songTrivia"] = $$createField29_0($$parsedSource["songTrivia"]);
        }
        if ("tidbits" in $$parsedSource) {
            $$parsedSource["tidbits"] = $$createField31_0($$parsedSource["tidbits"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField32_0($$parsedSource["sources"]);
        }
        if ("aiContext" in $$parsedSource) {
            $$parsedSource["aiContext"] = $$createField47_0($$parsedSource["aiContext"]);
        }
        return new TrackRecord($$parsedSource as Partial<TrackRecord>);
    }
}

export class URLImportDuplicateInfo {
    "exists": boolean;
    "trackId"?: string;
    "jobId"?: string;
    "metadataPath"?: string;
    "title"?: string;
    "artist"?: string;
    "album"?: string;
    "sourceUrl"?: string;
    "videoUrl"?: string;
    "matchReason"?: string;

    /** Creates a new URLImportDuplicateInfo instance. */
    constructor($$source: Partial<URLImportDuplicateInfo> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLImportDuplicateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): URLImportDuplicateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLImportDuplicateInfo($$parsedSource as Partial<URLImportDuplicateInfo>);
    }
}

export class UpdateInfo {
    "manifestUrl"?: string;
    "currentVersion"?: string;
    "latestVersion"?: string;
    "releaseDate"?: string;
    "releaseNotes"?: string;
    "downloadUrl"?: string;
    "platform"?: string;
    "available": boolean;
    "mandatory": boolean;
    "minimumVersion"?: string;
    "checkedAt"?: string;
    "status"?: string;
    "error"?: string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("mandatory" in $$source)) {
            this["mandatory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export class WorkerClassStats {
    "capacity": number;
    "active": number;
    "queued": number;
    "blocked": boolean;
    "blockedReason"?: string;
    "sharedCapacityOf"?: string;

    /** Creates a new WorkerClassStats instance. */
    constructor($$source: Partial<WorkerClassStats> = {}) {
        if (!("capacity" in $$source)) {
            this["capacity"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = 0;
        }
        if (!("queued" in $$source)) {
            this["queued"] = 0;
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerClassStats instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkerClassStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkerClassStats($$parsedSource as Partial<WorkerClassStats>);
    }
}

export class WorkerStats {
    "activeWorkers": number;
    "maxWorkers": number;
    "videoActive": number;
    "videoQueued": number;
    "audio": WorkerClassStats;
    "video": WorkerClassStats;
    "enrichment": WorkerClassStats;
    "lyrics": WorkerClassStats;
    "artwork": WorkerClassStats;
    "throttle": WorkerThrottleState;
    "blockedReason"?: string;

    /** Creates a new WorkerStats instance. */
    constructor($$source: Partial<WorkerStats> = {}) {
        if (!("activeWorkers" in $$source)) {
            this["activeWorkers"] = 0;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("videoActive" in $$source)) {
            this["videoActive"] = 0;
        }
        if (!("videoQueued" in $$source)) {
            this["videoQueued"] = 0;
        }
        if (!("audio" in $$source)) {
            this["audio"] = (new WorkerClassStats());
        }
        if (!("video" in $$source)) {
            this["video"] = (new WorkerClassStats());
        }
        if (!("enrichment" in $$source)) {
            this["enrichment"] = (new WorkerClassStats());
        }
        if (!("lyrics" in $$source)) {
            this["lyrics"] = (new WorkerClassStats());
        }
        if (!("artwork" in $$source)) {
            this["artwork"] = (new WorkerClassStats());
        }
        if (!("throttle" in $$source)) {
            this["throttle"] = (new WorkerThrottleState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkerStats {
        const $$createField4_0 = $$createType60;
        const $$createField5_0 = $$createType60;
        const $$createField6_0 = $$createType60;
        const $$createField7_0 = $$createType60;
        const $$createField8_0 = $$createType60;
        const $$createField9_0 = $$createType61;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField4_0($$parsedSource["audio"]);
        }
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField5_0($$parsedSource["video"]);
        }
        if ("enrichment" in $$parsedSource) {
            $$parsedSource["enrichment"] = $$createField6_0($$parsedSource["enrichment"]);
        }
        if ("lyrics" in $$parsedSource) {
            $$parsedSource["lyrics"] = $$createField7_0($$parsedSource["lyrics"]);
        }
        if ("artwork" in $$parsedSource) {
            $$parsedSource["artwork"] = $$createField8_0($$parsedSource["artwork"]);
        }
        if ("throttle" in $$parsedSource) {
            $$parsedSource["throttle"] = $$createField9_0($$parsedSource["throttle"]);
        }
        return new WorkerStats($$parsedSource as Partial<WorkerStats>);
    }
}

export class WorkerThrottleState {
    "active": boolean;
    "until"?: string;
    "reason"?: string;

    /** Creates a new WorkerThrottleState instance. */
    constructor($$source: Partial<WorkerThrottleState> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerThrottleState instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkerThrottleState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkerThrottleState($$parsedSource as Partial<WorkerThrottleState>);
    }
}

// Private type creation functions
const $$createType0 = PublicSettings.createFrom;
const $$createType1 = LibraryStats.createFrom;
const $$createType2 = LibraryHealth.createFrom;
const $$createType3 = WorkerStats.createFrom;
const $$createType4 = FacetBucket.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = BuildInfo.createFrom;
const $$createType7 = UpdateInfo.createFrom;
const $$createType8 = DiagnosticsInfo.createFrom;
const $$createType9 = Job.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ImportHistoryEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = TrackRecord.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Playlist.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = PlaybackState.createFrom;
const $$createType18 = PromptInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ToolStatus.createFrom;
const $$createType21 = ToolReadiness.createFrom;
const $$createType22 = $Create.Map($Create.Any, $$createType21);
const $$createType23 = RootInfo.createFrom;
const $$createType24 = $Create.Array($Create.Any);
const $$createType25 = JobStageStatuses.createFrom;
const $$createType26 = LibraryHealthIssue.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = LibraryManifestExclusions.createFrom;
const $$createType29 = LibraryManifestTrack.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = LibraryManifestPlaylist.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = LibraryManifestRating.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = LibraryManifestHistoryEntry.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = LibraryManifestSettings.createFrom;
const $$createType38 = $Create.Map($Create.Any, $Create.Any);
const $$createType39 = LibraryManifestPathReference.createFrom;
const $$createType40 = LibraryManifestTrackMetadata.createFrom;
const $$createType41 = LibraryManifestTrackPaths.createFrom;
const $$createType42 = LibraryManifestLyricsReference.createFrom;
const $$createType43 = LibraryManifestArtworkReference.createFrom;
const $$createType44 = LibraryManifestProvenance.createFrom;
const $$createType45 = MetadataLinks.createFrom;
const $$createType46 = SmartPlaylistRule.createFrom;
const $$createType47 = SmartPlaylistSort.createFrom;
const $$createType48 = SmartPlaylistMatch.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = SmartPlaylistExplanation.createFrom;
const $$createType51 = $Create.Array($$createType50);
const $$createType52 = SmartPlaylistTrackContext.createFrom;
const $$createType53 = $Create.Array($$createType46);
const $$createType54 = $Create.Nullable($$createType46);
const $$createType55 = SmartPlaylistPredicate.createFrom;
const $$createType56 = $Create.Nullable($$createType55);
const $$createType57 = TrackFileState.createFrom;
const $$createType58 = $Create.Array($$createType57);
const $$createType59 = songstore$0.SongAIContext.createFrom;
const $$createType60 = WorkerClassStats.createFrom;
const $$createType61 = WorkerThrottleState.createFrom;
